project:
  type: website
  output-dir: docs
  render: 
  - "*.qmd"      # Only render QMD files
  - "!slides/"   # EXPLICITLY IGNORE this folder for rendering
  resources: 
  - slides/
  - images/
  - coursework/

website:
  title: "Christy Choi"
  navbar:
    collapse: true
    collapse-below: lg
    background: light
    search: true
    reader-mode: true
    left: 
      - text: "About"
        href: about.qmd
      - text: "Coursework"
        href: coursework.qmd
      - text: "CV"
        href: cv.qmd
    right:
      - icon: github
        href: "https://github.com/christychoicc"

format:
  html:
    theme:
      #- cosmo
      #- brand
      light: [cosmo, flatly]
      dark: [cosmo, darkly]
    code-link: true

editor: visual


